'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NerdyPowerMeterVB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name,Int 1,Int 2,Int 3,Int 4,Int 5,Int 6,Int 7,Int 8,Int 9,Int 10,Int 11,Int 12,Int 13,Int 14,Int 15,Int 16,Int 17,Int 18,Int 19,Int 20,Int 21,Int 22,Int 23,Int 24,Int 25,Int 26,Int 27,Int 28,Int 29,Int 30,Int 31,Int 32,Int 33,Int 34,Int 35,Int 36,Int 37,Int 38,Int 39,Int 40
        '''Hills,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,7.5,7,6.5,6,5.5,5,4.5,4,3.5,3,2.5,2,2,2,2,2.5,3,3.5,4,4.5,5,4.5,4,3.5,3,2.5,2
        '''Pyramid,2,5,2,2,6,6,2,2,2,7,7,7,2,2,2,2,8,8,8,8,2,2,2,2,6,6,6,2,2,2,5,5,2,2,4,2,4,2,4,2
        '''Threshold,2,10,2,2,10,2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CyclingWorkouts() As String
            Get
                Return ResourceManager.GetString("CyclingWorkouts", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
